=== basedcount/lemmy-automoderator/src/schemas/post.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "rule": {
            "type": "string",
            "const": "post"
        },
        "community": {
            "type": "string"
        },
        "field": {
            "type": "string",
            "enum": [
                "title",
                "body",
                "link"
            ]
        },
        "match": {
            "type": "string"
        },
        "type": {
            "type": "string",
            "enum": [
                "exact",
                "regex"
            ]
        },
        "whitelist": {
            "type": "boolean"
        },
        "mod_exempt": {
            "type": "boolean"
        },
        "message": {
            "type": [
                "string",
                "null"
            ]
        },
        "removal_reason": {
            "type": [
                "string",
                "null"
            ]
        }
    },
    "required": [
        "rule",
        "community",
        "field",
        "match",
        "type",
        "whitelist",
        "mod_exempt",
        "message",
        "removal_reason"
    ]
}

=== basedcount/lemmy-automoderator/test/post.json
{
    "$schema": "https://raw.githubusercontent.com/ornato-t/lemmy-automoderator/master/src/schemas/post.json",
    "rule": "post",
    "community": "pcm",
    "field": "title",
    "type": "exact",
    "match": "ur ugly",
    "whitelist": false,
    "mod_exempt": true,
    "message": "The RoboJanny doesn't like you",
    "removal_reason": "arbitrary"
}
